FROM nginx:alpine

WORKDIR /
COPY dist /www/dist
COPY nginx/proxy.prod.conf /etc/nginx/conf.d/proxy.conf

# Expose is NOT supported by Heroku
# EXPOSE 5000

# Run the image as a non-root user
# RUN adduser -D myuser
# USER myuser

# Run the app.  CMD is required to run on Heroku
# $PORT is set by Heroku
CMD gunicorn --bind 0.0.0.0:$PORT wsgi